

POST http://localhost:3003/signup HTTP/1.1
Content-Type: application/json

{   
    "name": "Marceloose",
    "email":"Marcelom@gmail.com",
    "password": "123456",
    "role":"normal"
}

###
POST http://localhost:3003/login HTTP/1.1
Content-Type: application/json

{   
    "email":"gabriel13@gabriel.com",
    "password": "123456"
}


### 
GET http://localhost:3003/user HTTP/1.1
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ1ZjBkZDY1LTZjYzUtNDBmZi1iY2UzLWUxOWU0MGQ3NzJhYyIsImlhdCI6MTY1MTMxODExMiwiZXhwIjoxNjUxOTIyOTEyfQ.1dYgYg2qQievEmNDwNdxnsaWaI4PtW_XWRVFm0ED20I


### 
Post http://localhost:3003/user HTTP/1.1
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ1ZjBkZDY1LTZjYzUtNDBmZi1iY2UzLWUxOWU0MGQ3NzJhYyIsImlhdCI6MTY1MTMxODExMiwiZXhwIjoxNjUxOTIyOTEyfQ.1dYgYg2qQievEmNDwNdxnsaWaI4PtW_XWRVFm0ED20I

{  
    "followedUserId": "d5f0dd65-6cc5-40ff-bce3-e19e40d772ac"
}
###

POST http://localhost:3003/recipes HTTP/1.1
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ1ZjBkZDY1LTZjYzUtNDBmZi1iY2UzLWUxOWU0MGQ3NzJhYyIsImlhdCI6MTY1MTMxODExMiwiZXhwIjoxNjUxOTIyOTEyfQ.1dYgYg2qQievEmNDwNdxnsaWaI4PtW_XWRVFm0ED20I

{   
   "title":" abobaora ", 
   "description":"pedacos de abororas"
}

###

GET http://localhost:3003/feed HTTP/1.1
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjcxYTU4OTQ1LTJjMjUtNGY3My05MGY0LTYzNTg0Mjk4YzFmYyIsImlhdCI6MTY1MTM4MDg1NiwiZXhwIjoxNjUxOTg1NjU2fQ.U0S6O2yUWhCqMAg6mJhOcxWQdyd9ZIJd3lVrvcjnjTc



####
# Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ1ZjBkZDY1LTZjYzUtNDBmZi1iY2UzLWUxOWU0MGQ3NzJhYyIsImlhdCI6MTY1MTMxODExMiwiZXhwIjoxNjUxOTIyOTEyfQ.1dYgYg2qQievEmNDwNdxnsaWaI4PtW_XWRVFm0ED20I


