

POST http://localhost:3003/signup HTTP/1.1
Content-Type: application/json

{ 
    "name": "Jieun lee" ,
    "email": "jieuewns@gmail" ,
    "role": "ADMIN" ,
    "password": "123456"
}

###

POST http://localhost:3003/login HTTP/1.1
Content-Type: application/json

{ 

    "email": "jieuewns@gmail" ,
    "password": "123456"
}

###

GET http://localhost:3003/users HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkOWQ4YjkzLTc3OTYtNDhjZC1iMWVjLWViNTVlYzA4ODJiNiIsImlhdCI6MTY1MTU3Mjg5NSwiZXhwIjoxNjUxNjA4ODk1fQ.gymlKtVhCZef2vC8ho-xmuhosE1kZpwEUeOy44zzHFk

