

POST http://localhost:3003/competitor HTTP/1.1
Content-Type: application/json

{ 
        "competition":  "100m",
               "name": "Gabriel12",
               "value": 10, 
}



###

POST http://localhost:3003/competition HTTP/1.1
Content-Type: application/json

{ 
        "competitionName":"darts",
        "status": "open"
}

###

POST http://localhost:3003/competition HTTP/1.1
Content-Type: application/json

{ 
        "competitionName":"100m",
        "status": "open"
}


